#!/usr/bin/env bash
#MISE hide=true
#MISE quiet=true

set -eu

GENERATED_PATH="$MISE_PROJECT_ROOT/apps/server/db/src/generated.rs"

disable_warnings() {
  DIRECTIVES="#![allow(warnings, unused, clippy::all)]"

  if ! head -n 1 "$GENERATED_PATH" | grep -qF "$DIRECTIVES"; then
    sed -i "1s/^/$DIRECTIVES\n/" "$GENERATED_PATH"
  fi
}

main() {
  disable_warnings
}

main
