// This file was generated by [rspc](https://github.com/specta-rs/rspc). Do not edit this file manually.

export type Procedures = {
  queries: { key: "users.read"; input: number; result: UserResponseDto }
  mutations: never
  subscriptions: never
}

export type UserResponseDto = { id: number; email: string; username: string }
