// This file was generated by [rspc](https://github.com/specta-rs/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "auth.signin", input: SigninRequestDto, result: null } | 
        { key: "profile.read", input: string, result: ProfileDto },
    mutations: 
        { key: "auth.signup", input: SignupRequestDto, result: null },
    subscriptions: never
};

export type ProfileDto = { id: string; username: string }

export type SigninRequestDto = { email: string; password: string }

export type SignupRequestDto = { email: string; password: string; username: string }
