[workspace]
members = [
    "apps/server/crates/api",
    "apps/server/crates/app",
    "apps/server/crates/domain",
    "apps/server/crates/infra", "apps/server/crates/server",
]
package = { edition = "2021" }
resolver = "2"

[profile.release]
lto = "fat"
strip = true
codegen-units = 1
panic = "abort"
rpath = false

[profile.dev.package."*"]
debug = false
