services:
  client:
    build:
      context: apps/client
    container_name: pse-forum-client
    environment:
      PORT: "${SERVER_PORT:-80}" # default to 80 but allow override
      VITE_SERVER_URL: http://server:3000
    ports: ["${SERVER_PORT:-80}:80"]

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: pse-forum-server
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    ports: ["3000:3000"]

  postgres:
    image: postgres:latest
    container_name: pse-forum-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    tmpfs: [/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
