services:
  client:
    image: ghcr.io/privacy-scaling-explorations/pse-forums-client:latest
    container_name: pse-forum-client
    environment:
      VITE_SERVER_URL: http://server:3000
    ports: ["80:80"]

  # used during local development only
  mail:
    image: inbucket/inbucket:stable
    container_name: pse-forum-mail
    restart: unless-stopped
    ports: ["9000:9000", "2500:2500", "1100:1100"]

  server:
    image: ghcr.io/privacy-scaling-explorations/pse-forums-server:latest
    container_name: pse-forum-server
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      CLIENT_URL: http://localhost # must be url on external network (not docker's), with docker compose the client is served with nginx on port 80
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      EMAIL_FROM: "${EMAIL_FROM:-pse-forum@noreply.com}"
      EMAIL_HOST: pse-forum-mail # mail service container name if using inbucket
      EMAIL_PORT: "${EMAIL_PORT:-2500}"
      JWT_SECRET: "${JWT_SECRET:-secret}"
      USE_INBUCKET: "${USE_INBUCKET:-false}"
      VITE_SERVER_URL: "${VITE_SERVER_URL:-http://localhost:3000}"
    ports: ["3000:3000"]

  postgres:
    image: postgres:latest
    container_name: pse-forum-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    tmpfs: [/var/lib/postgresql/data]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
