services:
  client:
    container_name: pse-forum-client
    build:
      context: ./apps/client
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://localhost:3001
      - NODE_ENV=development
    ports: 
      - "3000:3000"
    volumes:
      - ./apps/client:/workspace/apps/client
      - ./apps/shared:/workspace/apps/shared
      - /workspace/apps/client/node_modules
    working_dir: /workspace/apps/client
    command: npm run dev
    depends_on:
      - api

  api:
    container_name: pse-forum-api
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    environment:
      - PORT=3001
      - NODE_ENV=development
      - HOST=0.0.0.0
    ports: 
      - "3001:3001"
    volumes:
      - ./apps/api:/workspace/apps/api
      - ./apps/shared:/workspace/apps/shared
      - /workspace/apps/api/node_modules
    working_dir: /workspace/apps/api
    command: sh -c "cd ../shared && npm install && npm run build && cd ../api && npm install && npm run dev"

volumes:
  client_modules:
  api_modules:
  shared_modules:

networks:
  default:
    name: pse-forum-network
