[env]
BANDADA_URL = "http://localhost:3000"
CLIENT_URL = "http://localhost:5173"
DATABASE_URL = "postgres://postgres:postgres@localhost:5432/postgres"
EMAIL_FROM = "pse-forum@noreply.com"
EMAIL_HOST = "localhost"
#EMAIL_PASSWORD=not needed during local dev with inbucket
#EMAIL_USERNAME=not needed during local dev with inbucket
EMAIL_PORT = 2500
JWT_SECRET = "very-strong-secret"
PRISMA_GEN_TS_BINDINGS_PATH = "{{config_root}}/apps/client/src/lib/bindings.ts"
USE_INBUCKET = true
VITE_SERVER_URL = "http://localhost:3000"
_ = { file = ".env.yaml" }

[tools]
bun = "latest"
"cargo:cargo-nextest" = "latest"
flyctl = "latest"
hurl = "latest"
lefthook = "latest"
rust = "latest"

[tasks.add-shadcn-component]
run = "bunx --bun shadcn@latest add {{arg(name=\"component\")}}"
alias = "ac"
description = "Add a new shadcn component"

[tasks.build-client]
run = "bun vite build"
alias = "bc"
description = "Build client"
dir = "apps/client"
sources = [
    "apps/client/**/*",
    "!apps/client/dist/**",
    "!apps/client/node_modules/**",
]
outputs.auto = true
depends = ["gen-ts"]

[tasks.build-server]
run = "cargo build -r"
alias = "bs"
description = "Build server"
dir = "apps/server"
sources = ["apps/server/**/*.rs"]
outputs.auto = true

[tasks.db-deploy]
dir = "apps/server/db"
description = "Run migrations on hosted DB"
run = "DATABASE_URL=$DATABASE_URL_PROD cargo run --bin prisma -F bin -- migrate deploy"

[tasks.db-start]
run = "docker compose up -d postgres"
alias = "dbs"
description = "Run local dockerized postgres"

[tasks.dev]
alias = "d"
depends = ["dev-client", "dev-server"]
description = "Start everything in dev mode"

[tasks.dev-client]
run = "bun vite dev"
alias = "dc"
dir = "apps/client"
depends = ["install-node-modules", "gen-ts"]
sources = [
    "apps/client/**/*",
    "!apps/client/dist/**",
    "!apps/client/node_modules/**",
]
outputs.auto = true
description = "Run client in dev mode"

[tasks.dev-server]
run = ["docker compose up mail -d", "mise r db-reset && cargo run --bin api"]
alias = "ds"
description = "Run server in dev mode"

[tasks.freedit]
dir = "apps/freedit"
run = "cargo run -r --bin freedit"
description = "Start legacy freedit server"

[tasks.gen-ts]
run = "cargo run --bin bindings"
hide = true
description = "Generate r(s)pc ts bindings"

[tasks.install-node-modules]
run = "bun i"
hide = true
sources = ["package.json", "apps/client/package.json"]
outputs = ["bun.lockb"]

[tasks.prisma]
run = "cargo run -F bin --bin prisma --"
alias = "p"
dir = "apps/server/db"
depends_post = ["post-gen-rs"]
description = "Run prisma CLI"

[tasks.restart]
run = """
mise r down && \
docker compose build --no-cache && \
mise run up
"""
description = "Restart everything (rebuild dockerized services)"

[tasks.seed]
run = "cargo run --bin seed"
description = "Seed local DB"
hide = true

[tasks.test-rs]
alias = "tr"
run = "cargo nextest run"
description = "Run Rust tests"

[tasks.test-hurl]
dir = "apps/server/api/test/integration"
run = "hurl --test *"
alias = "th"
description = "Run http integration tests"
