#:schema https://gist.githubusercontent.com/sripwoud/144f811fbaafe2765f894d81cb1d986c/raw/7bb569892c31e9aa692c0fb3808af9134cfe9764/mise-task.json

[env]
DATABASE_URL = "postgresql://postgres:postgres@127.0.0.1:54322/postgres"
PRISMA_GEN_RS_CLIENT_PATH = "{{config_root}}/db/prisma/src/generated.rs"
PRISMA_GEN_TS_BINDINGS_PATH = "{{config_root}}/apps/client/src/lib/bindings.ts"
SUPABASE_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0"
SUPABASE_JWT_SECRET = "super-secret-jwt-token-with-at-least-32-characters-long"
SUPABASE_URL = "http://127.0.0.1:54321"
SUPABASE_WORKDIR = "db"
VITE_SERVER_URL = "http://localhost:3000"

[tools]
bun = "latest"
"cargo:cargo-nextest" = "latest"
lefthook = "latest"
rust = "latest"

[tasks]
add-shadcn-component = { alias = "ac", dir = "apps/client", run = 'bunx --bun shadcn@latest add {{arg(name="component")}}' }
build-client = { alias = "bc", dir = "apps/client", run = "bun vite build", sources = [
    "apps/client/**/*",
    "!apps/client/dist/**",
    "!apps/client/node_modules/**",
], outputs.auto = true, depends = [
    "gen-ts",
] }
build-server = { alias = "bs", dir = "apps/server", run = "cargo build -r", sources = [
    "apps/server/**/*.rs",
], outputs.auto = true }
db-reset = { alias = "dbr", run = "bun supabase db reset && mise r p migrate deploy" }
db-start = { alias = "dbs", description = "Run local postgres instance (with supabase docker container)", run = "bun supabase start" }
dev = { alias = "d", depends = ["dev-client", "dev-server"] }
dev-client = { alias = "dc", dir = "apps/client", run = "bun vite dev", depends = [
    "install-node-modules",
    "gen-ts",
], wait_for = [
    "db-start",
] }
dev-server = { alias = "ds", run = ["mise r db-start", "cargo run --bin api"] }
freedit = { dir = "apps/freedit", run = "cargo run -r --bin freedit" }
install-node-modules = { hide = true, run = "bun i", sources = [
    "package.json",
    "apps/client/package.json",
], outputs = [
    "bun.lockb",
] }
gen-ts = { run = "cargo run --bin bindings", hide = true }
prisma = { alias = "p", dir = "db/prisma", description = "Run prisma CLI by connecting to the DB with pgbouncer", run = "cargo run -F bin --", depends_post = [
    "post-gen-rs",
] }
start = { alias = "s", depends = ["db-start", "start-server", "start-client"] }
start-client = { alias = "sc", depends = [
    "install-node-modules",
    "build-client",
], dir = "apps/client", run = "bun vite preview", sources = [
    "apps/client/**/*",
    "!apps/client/dist/**",
    "!apps/client/node_modules/**",
], outputs.auto = true }
start-server = { alias = "ss", dir = "apps/server", run = "cargo run -r --bin api", sources = [
    "apps/server/**/*.rs",
], outputs.auto = true, depends = [
    "gen-rs",
] }
test = { alias = "t", run = "cargo nextest run" }
