/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router"

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as InnIidImport } from "./routes/inn/$iid"

// Create Virtual Routes

const SoloLazyImport = createFileRoute("/solo")()
const RssLazyImport = createFileRoute("/rss")()
const NotificationsLazyImport = createFileRoute("/notifications")()
const IndexLazyImport = createFileRoute("/")()
const InnIndexLazyImport = createFileRoute("/inn/")()

// Create/Update Routes

const SoloLazyRoute = SoloLazyImport.update({
  id: "/solo",
  path: "/solo",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/solo.lazy").then((d) => d.Route))

const RssLazyRoute = RssLazyImport.update({
  id: "/rss",
  path: "/rss",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/rss.lazy").then((d) => d.Route))

const NotificationsLazyRoute = NotificationsLazyImport.update({
  id: "/notifications",
  path: "/notifications",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/notifications.lazy").then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/index.lazy").then((d) => d.Route))

const InnIndexLazyRoute = InnIndexLazyImport.update({
  id: "/inn/",
  path: "/inn/",
  getParentRoute: () => rootRoute,
} as any).lazy(() => import("./routes/inn/index.lazy").then((d) => d.Route))

const InnIidRoute = InnIidImport.update({
  id: "/inn/$iid",
  path: "/inn/$iid",
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    "/notifications": {
      id: "/notifications"
      path: "/notifications"
      fullPath: "/notifications"
      preLoaderRoute: typeof NotificationsLazyImport
      parentRoute: typeof rootRoute
    }
    "/rss": {
      id: "/rss"
      path: "/rss"
      fullPath: "/rss"
      preLoaderRoute: typeof RssLazyImport
      parentRoute: typeof rootRoute
    }
    "/solo": {
      id: "/solo"
      path: "/solo"
      fullPath: "/solo"
      preLoaderRoute: typeof SoloLazyImport
      parentRoute: typeof rootRoute
    }
    "/inn/$iid": {
      id: "/inn/$iid"
      path: "/inn/$iid"
      fullPath: "/inn/$iid"
      preLoaderRoute: typeof InnIidImport
      parentRoute: typeof rootRoute
    }
    "/inn/": {
      id: "/inn/"
      path: "/inn"
      fullPath: "/inn"
      preLoaderRoute: typeof InnIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexLazyRoute
  "/notifications": typeof NotificationsLazyRoute
  "/rss": typeof RssLazyRoute
  "/solo": typeof SoloLazyRoute
  "/inn/$iid": typeof InnIidRoute
  "/inn": typeof InnIndexLazyRoute
}

export interface FileRoutesByTo {
  "/": typeof IndexLazyRoute
  "/notifications": typeof NotificationsLazyRoute
  "/rss": typeof RssLazyRoute
  "/solo": typeof SoloLazyRoute
  "/inn/$iid": typeof InnIidRoute
  "/inn": typeof InnIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/": typeof IndexLazyRoute
  "/notifications": typeof NotificationsLazyRoute
  "/rss": typeof RssLazyRoute
  "/solo": typeof SoloLazyRoute
  "/inn/$iid": typeof InnIidRoute
  "/inn/": typeof InnIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/notifications" | "/rss" | "/solo" | "/inn/$iid" | "/inn"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/notifications" | "/rss" | "/solo" | "/inn/$iid" | "/inn"
  id:
    | "__root__"
    | "/"
    | "/notifications"
    | "/rss"
    | "/solo"
    | "/inn/$iid"
    | "/inn/"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  NotificationsLazyRoute: typeof NotificationsLazyRoute
  RssLazyRoute: typeof RssLazyRoute
  SoloLazyRoute: typeof SoloLazyRoute
  InnIidRoute: typeof InnIidRoute
  InnIndexLazyRoute: typeof InnIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  NotificationsLazyRoute: NotificationsLazyRoute,
  RssLazyRoute: RssLazyRoute,
  SoloLazyRoute: SoloLazyRoute,
  InnIidRoute: InnIidRoute,
  InnIndexLazyRoute: InnIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/notifications",
        "/rss",
        "/solo",
        "/inn/$iid",
        "/inn/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/notifications": {
      "filePath": "notifications.lazy.tsx"
    },
    "/rss": {
      "filePath": "rss.lazy.tsx"
    },
    "/solo": {
      "filePath": "solo.lazy.tsx"
    },
    "/inn/$iid": {
      "filePath": "inn/$iid.tsx"
    },
    "/inn/": {
      "filePath": "inn/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
