[package]
name = "services"
edition.workspace = true

[dependencies]
async-trait = "0.1.85"
derive_more = { version = "1.0.0", features = ["constructor"] }
domain = { path = "../domain" }
infra = { path = "../infra" }
rspc = "0.3.1"
serde = { version = "1.0.217", features = ["derive"] }
specta = "1.0.5"
thiserror = "2.0.11"
