[package]
name = "services"
edition.workspace = true

[dependencies]
async-trait = "0.1.85"
derive_more = { version = "1.0.0", features = ["constructor"] }
domain = { path = "../domain" }
infra = { path = "../infra" }
thiserror = "2.0.11"
