[package]
name = "infra"
edition.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
db = { path = "../db" }
derive_more.workspace = true
domain = { path = "../domain" }
serde.workspace = true
specta.workspace = true
thiserror.workspace = true
