[package]
name = "api"
edition.workspace = true

[dependencies]
axum.workspace = true
derive_more.workspace = true
domain = { path = "../domain" }
prisma = { path = "../../../prisma" }
rspc.workspace = true
serde.workspace = true
services = { path = "../services" }
specta.workspace = true
